version: '3'
services:
  guilmor_site:
    container_name: guilmor_site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
networks:
  default:
    external: true
    name: docker_default