version: '3.8'
services:
  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:4200' 
      - '443:443' 
      - '81:81'
    networks:
      - vps_gulliver
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks:
  default: 
  vps_gulliver:
    external: true